# Generated by Django 4.2.3 on 2023-07-16 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user_profile_pic_user_usertype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_category', models.CharField(choices=[('Formal', 'Formal'), ('Sports', 'Sports'), ('Casual', 'Casual')], max_length=100)),
                ('product_brand', models.CharField(choices=[('Skechers', 'Skechers'), ('Asics', 'Asics'), ('New Balance', 'New Balance'), ('Adidas', 'Adidas'), ('Bata', 'Bata')], max_length=100)),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.PositiveIntegerField()),
                ('product_size', models.CharField(choices=[('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], max_length=100)),
                ('product_pic', models.ImageField(upload_to='profile_pic/')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
